/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Factory.Factory;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author su
 */
public class FrmMain extends javax.swing.JFrame {

    protected Factory main = new Factory();
    
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
    
    FrmAbout about;
    private void showFrmAbout(){
        try {
            // TODO add your handling code here:
            if (about == null || about.isVisible()) {
               about = new FrmAbout();
                mainPane.add(about);
            }
            about.moveToFront();
            about.setSelected(true);
            about.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnIPaket = new javax.swing.JMenuItem();
        mnIPelanggan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnITransaksi = new javax.swing.JMenuItem();
        mnIBatal = new javax.swing.JMenuItem();
        mnIRekap = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnManual = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenu2.setText("Master");

        mnIPaket.setText("Paket");
        mnIPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIPaketActionPerformed(evt);
            }
        });
        jMenu2.add(mnIPaket);

        mnIPelanggan.setText("Pelanggan");
        mnIPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(mnIPelanggan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        mnITransaksi.setText("Transaksi Layanan");
        mnITransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnITransaksiActionPerformed(evt);
            }
        });
        jMenu3.add(mnITransaksi);

        mnIBatal.setText("Batal Transaksi");
        mnIBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIBatalActionPerformed(evt);
            }
        });
        jMenu3.add(mnIBatal);

        mnIRekap.setText("Rekap Transaksi");
        mnIRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIRekapActionPerformed(evt);
            }
        });
        jMenu3.add(mnIRekap);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Help");

        mnManual.setText("Manual");
        jMenu1.add(mnManual);

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu1.add(mnAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private FrmPaket paket;
    private void mnIPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIPaketActionPerformed
        try {
            // TODO add your handling code here:
            if (paket == null || paket.isVisible()) {
               paket = new FrmPaket(this);
                mainPane.add(paket);
            }
            paket.moveToFront();
            paket.setSelected(true);
            paket.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnIPaketActionPerformed
    private FrmPelanggan pelanggan;
    private void mnIPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIPelangganActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (pelanggan == null || pelanggan.isVisible()) {
               pelanggan = new FrmPelanggan(this);
                mainPane.add(pelanggan);
            }
            pelanggan.moveToFront();
            pelanggan.setSelected(true);
            pelanggan.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnIPelangganActionPerformed
    private FrmTransaksi transaksi;
    private void mnITransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnITransaksiActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (transaksi == null || transaksi.isVisible()) {
               transaksi = new FrmTransaksi(this);
                mainPane.add(transaksi);
            }
            transaksi.moveToFront();
            transaksi.setSelected(true);
            transaksi.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnITransaksiActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        main.Close();
    }//GEN-LAST:event_formWindowClosed
    private FrmRekapTransaksi rekap;
    private void mnIRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIRekapActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (rekap == null || rekap.isVisible()) {
               rekap = new FrmRekapTransaksi(this);
                mainPane.add(rekap);
            }
            rekap.moveToFront();
            rekap.setSelected(true);
            rekap.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnIRekapActionPerformed
    FrmBatalTransaksi btransaksi;
    private void mnIBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIBatalActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (btransaksi == null || btransaksi.isVisible()) {
               btransaksi = new FrmBatalTransaksi(this);
                mainPane.add(btransaksi);
            }
            btransaksi.moveToFront();
            btransaksi.setSelected(true);
            btransaksi.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnIBatalActionPerformed
    
    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        showFrmAbout();
    }//GEN-LAST:event_mnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mainPane;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnIBatal;
    private javax.swing.JMenuItem mnIPaket;
    private javax.swing.JMenuItem mnIPelanggan;
    private javax.swing.JMenuItem mnIRekap;
    private javax.swing.JMenuItem mnITransaksi;
    private javax.swing.JMenuItem mnManual;
    // End of variables declaration//GEN-END:variables
}
